### ISSUE TITLE
[JOSS] Contributions statement and documentation

### ISSUE THREAD

**Issue by joezuntz** [jronayne/PyTransport#5]
JOSS requires that you have a statement with the code detailing this:
```
Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
```

I couldn't see anything about contributions, though the other things are mentioned on the website.
Also you might want to link to transportmethod.com in the README.md.

**Comment by jronayne** [comment]
I have now update the README.md file in the main repo to contain a section on contributions and issues.
