### ISSUE TITLE
[JOSS] Python 3

### ISSUE THREAD

**Issue by joezuntz** [jronayne/PyTransport#6]
The installation instructions say that the code will work on python3, but I get an error:
TabError: inconsistent use of tabs and spaces in indentation
in the PyTransport/PyTransSetup.py file

**Comment by joezuntz** [comment]
This seems to come from this line:
vd[i] = sym.simplify(V.diff(f[i]))

**Comment by ronoxe** [comment]
I have corrected for the inconsistency of tabs and spacing in PyTransSetup.py script. It should no long throw any errors.

**Comment by jronayne** [comment]
I have corrected for the inconsistency in the use of tabs and spacing in the PyTransSetup.py file. It should no longer throw out any errors.

**Comment by joezuntz** [comment]
Thanks - this works for me now, though in some of the examples I had to add parentheses to print calls.
i.e. "print x" -> "print(x)"
Thanks!
